routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'changeprofile', 'as' => 'changeprofile.'], function () {
    Route::put('', ['as' => 'update', 'uses' => 'HomeController@updatepropfile']);
    Route::get('/edit', ['as' => 'edit', 'uses' => 'HomeController@editprofile']);
    Route::post('', ['as' => 'fotoup', 'uses' => 'HomeController@uploadFoto']);
});

Route::group(['prefix' => 'changepassword', 'as' => 'changepassword.'], function () {
    Route::post('', ['as' => 'update', 'uses' => 'HomeController@updatepassword']);
    Route::get('/edit', ['as' => 'edit', 'uses' => 'HomeController@editpassword']);
});

Route::group(['prefix' => 'jabatan', 'as' => 'jabatan.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'JabatanController@index']);
    Route::post('', ['as' => 'store', 'uses' => 'JabatanController@store']);
    Route::get('/create', ['as' => 'create', 'uses' => 'JabatanController@create']);
    Route::get('/{jabatan}', ['as' => 'show', 'uses' => 'JabatanController@show']);
    Route::put('/{jabatan}', ['as' => 'update', 'uses' => 'JabatanController@update']);
    Route::delete('/{jabatan}', ['as' => 'destroy', 'uses' => 'JabatanController@destroy']);
    Route::get('/{jabatan}/edit', ['as' => 'edit', 'uses' => 'JabatanController@edit']);
});

Route::group(['prefix' => 'kategori', 'as' => 'kategori.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'KatIbadahController@index'])->middleware('permission:read katibadah');
    Route::post('', ['as' => 'store', 'uses' => 'KatIbadahController@store'])->middleware('permission:create katibadah');
    Route::get('/create', ['as' => 'create', 'uses' => 'KatIbadahController@create'])->middleware('permission:create katibadah');
    Route::get('/{kategori}', ['as' => 'show', 'uses' => 'KatIbadahController@show'])->middleware('permission:read katibadah');
    Route::put('/{kategori}', ['as' => 'update', 'uses' => 'KatIbadahController@update'])->middleware('permission:update katibadah');
    Route::delete('/{kategori}', ['as' => 'destroy', 'uses' => 'KatIbadahController@destroy'])->middleware('permission:delete katibadah');
    Route::get('/{kategori}/edit', ['as' => 'edit', 'uses' => 'KatIbadahController@edit'])->middleware('permission:update katibadah');
});

Route::group(['prefix' => 'setKeuangan', 'as' => 'setKeuangan.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'SetKeuanganController@index'])->middleware('permission:read setkeuangan');
    Route::post('', ['as' => 'store', 'uses' => 'SetKeuanganController@store'])->middleware('permission:create setkeuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'SetKeuanganController@create'])->middleware('permission:create setkeuangan');
    Route::get('/{setKeuangan}', ['as' => 'show', 'uses' => 'SetKeuanganController@show'])->middleware('permission:read setkeuangan');
    Route::put('/{setKeuangan}', ['as' => 'update', 'uses' => 'SetKeuanganController@update'])->middleware('permission:update setkeuangan');
    Route::delete('/{setKeuangan}', ['as' => 'destroy', 'uses' => 'SetKeuanganController@destroy'])->middleware('permission:delete setkeuangan');
    Route::get('/{setKeuangan}/edit', ['as' => 'edit', 'uses' => 'SetKeuanganController@edit'])->middleware('permission:update setkeuangan');
});

Route::group(['prefix'=>'jemaat','as'=>'jemaat.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'JemaatController@index'])->middleware('permission:read jemaat');
    Route::post('', ['as' => 'store', 'uses' => 'JemaatController@store'])->middleware('permission:create jemaat');
    Route::get('/create', ['as' => 'create', 'uses' => 'JemaatController@create'])->middleware('permission:create jemaat');
    Route::get('/{jemaat}', ['as' => 'show', 'uses' => 'JemaatController@show'])->middleware('permission:read jemaat');
    Route::put('/{jemaat}', ['as' => 'update', 'uses' => 'JemaatController@update'])->middleware('permission:update jemaat');
    Route::post('/{jemaat}', ['as' => 'fotoup', 'uses' => 'JemaatController@uploadFoto']);
    Route::delete('/{jemaat}', ['as' => 'destroy', 'uses' => 'JemaatController@destroy'])->middleware('permission:delete jemaat');
    Route::get('/{jemaat}/edit', ['as' => 'edit', 'uses' => 'JemaatController@edit'])->middleware('permission:update jemaat');
});

Route::group(['prefix'=>'baptis','as'=>'baptis.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'BaptisController@index'])->middleware('permission:read baptis');
    Route::post('', ['as' => 'store', 'uses' => 'BaptisController@store'])->middleware('permission:create baptis');
    Route::get('/create', ['as' => 'create', 'uses' => 'BaptisController@create'])->middleware('permission:create baptis');
    Route::get('/{baptis}', ['as' => 'show', 'uses' => 'BaptisController@show'])->middleware('permission:read baptis');
    Route::put('/{baptis}', ['as' => 'update', 'uses' => 'BaptisController@update'])->middleware('permission:update baptis');
    Route::delete('/{baptis}', ['as' => 'destroy', 'uses' => 'BaptisController@destroy'])->middleware('permission:delete baptis');
    Route::get('/{baptis}/edit', ['as' => 'edit', 'uses' => 'BaptisController@edit'])->middleware('permission:update baptis');
});

Route::group(['prefix'=>'sidi','as'=>'sidi.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SidiController@index'])->middleware('permission:read sidi');
    Route::post('', ['as' => 'store', 'uses' => 'SidiController@store'])->middleware('permission:create sidi');
    Route::get('/create', ['as' => 'create', 'uses' => 'SidiController@create'])->middleware('permission:create sidi');
    Route::get('/{sidi}', ['as' => 'show', 'uses' => 'SidiController@show'])->middleware('permission:read sidi');
    Route::put('/{sidi}', ['as' => 'update', 'uses' => 'SidiController@update'])->middleware('permission:update sidi');
    Route::delete('/{sidi}', ['as' => 'destroy', 'uses' => 'SidiController@destroy'])->middleware('permission:delete sidi');
    Route::get('/{sidi}/edit', ['as' => 'edit', 'uses' => 'SidiController@edit'])->middleware('permission:update sidi');
});

Route::group(['prefix'=>'nikah','as'=>'nikah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'NikahController@index'])->middleware('permission:read nikah');
    Route::post('', ['as' => 'store', 'uses' => 'NikahController@store'])->middleware('permission:create nikah');
    Route::get('/create', ['as' => 'create', 'uses' => 'NikahController@create'])->middleware('permission:create nikah');
    Route::get('/{nikah}', ['as' => 'show', 'uses' => 'NikahController@show'])->middleware('permission:read nikah');
    Route::put('/{nikah}', ['as' => 'update', 'uses' => 'NikahController@update'])->middleware('permission:update nikah');
    Route::delete('/{nikah}', ['as' => 'destroy', 'uses' => 'NikahController@destroy'])->middleware('permission:delete nikah');
    Route::get('/{nikah}/edit', ['as' => 'edit', 'uses' => 'NikahController@edit'])->middleware('permission:update nikah');
});

Route::group(['prefix'=>'pengumuman','as'=>'pengumuman.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'PengumumanController@index'])->middleware('permission:read pengumuman');
    Route::post('', ['as' => 'store', 'uses' => 'PengumumanController@store'])->middleware('permission:create pengumuman');
    Route::get('/create', ['as' => 'create', 'uses' => 'PengumumanController@create'])->middleware('permission:create pengumuman');
    Route::get('/{pengumuman}', ['as' => 'show', 'uses' => 'PengumumanController@show'])->middleware('permission:read pengumuman');
    Route::put('/{pengumuman}', ['as' => 'update', 'uses' => 'PengumumanController@update'])->middleware('permission:update pengumuman');
    Route::delete('/{pengumuman}', ['as' => 'destroy', 'uses' => 'PengumumanController@destroy'])->middleware('permission:delete pengumuman');
    Route::get('/{pengumuman}/edit', ['as' => 'edit', 'uses' => 'PengumumanController@edit'])->middleware('permission:update pengumuman');
});

Route::group(['prefix'=>'ibadah','as'=>'ibadah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'IbadahController@index'])->middleware('permission:read ibadah');
    Route::post('', ['as' => 'store', 'uses' => 'IbadahController@store'])->middleware('permission:create ibadah');
    Route::get('/create', ['as' => 'create', 'uses' => 'IbadahController@create'])->middleware('permission:create ibadah');
    Route::get('/{ibadah}', ['as' => 'show', 'uses' => 'IbadahController@show'])->middleware('permission:read ibadah');
    Route::put('/{ibadah}', ['as' => 'update', 'uses' => 'IbadahController@update'])->middleware('permission:update ibadah');
    Route::delete('/{ibadah}', ['as' => 'destroy', 'uses' => 'IbadahController@destroy'])->middleware('permission:delete ibadah');
    Route::get('/{ibadah}/edit', ['as' => 'edit', 'uses' => 'IbadahController@edit'])->middleware('permission:update ibadah');
});

Route::group(['prefix'=>'keuangan','as'=>'keuangan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'KeuanganController@index'])->middleware('permission:read keuangan');
    Route::post('', ['as' => 'store', 'uses' => 'KeuanganController@store'])->middleware('permission:create keuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'KeuanganController@create'])->middleware('permission:create keuangan');

resources/views/home.blade.php
@extends('layouts.base')

@section('css')
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- iCheck -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{ asset('plugins/jqvmap/jqvmap.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
@endsection

@section('title_head')
    Dashboard
@endsection

@section('bread')
    <li class="breadcrumb-item active">Dashboard</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-6 col-6">
        <!-- small box -->
        <div class="small-box bg-olive">
            <div class="inner">
                <h3>{{ $jum_jemaat }}</h3>
                <p>JEMAAT</p>
            </div>
            <div class="icon">
                <i class="fas fa-users"></i>
            </div>
            <a href="{{ route('jemaat.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-6 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>{{ $jum_ibadah }}</h3>
                <p>Jadwal Ibadah</p>
            </div>
            <div class="icon">
                <i class="fas fa-bible"></i>
            </div>
            <a href="{{ route('ibadah.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-6">
        <!-- small box -->
        <div class="small-box bg-purple">
            <div class="inner">
                <h3>{{ $jum_baptis }}</h3>
                <p>Jadwal Pembabtisan</p>
            </div>
            <div class="icon">
                <i class="fas fa-pray"></i>
            </div>
            <a href="{{ route('baptis.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-6">
        <!-- small box -->
        <div class="small-box bg-teal">
            <div class="inner">
                <h3>{{ $jum_sidi }}</h3>
                <p>Jadwal SIDI</p>
            </div>
            <div class="icon">
                <i class="fas fa-user-friends"></i>
            </div>
            <a href="{{ route('sidi.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-4 col-6">
        <!-- small box -->
        <div class="small-box bg-pink">
            <div class="inner">
                <h3>{{ $jum_nikah }}</h3>
                <p>Jadwal Pernikahan</p>
            </div>
            <div class="icon">
                <i class="fas fa-people-carry"></i>
            </div>
            <a href="{{ route('nikah.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card card-outline">
            <div class="card-header">
                <h3 class="card-title">Pengumuman</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 322px;">
                <table class="table table-striped table-striped">
                    <tbody>
                        @foreach ($pengumumans as $pengumuman)
                        <tr>
                            <td style="width: 20%"><a href="#" class="" data-toggle="modal" data-target="#detailPengumuman{{ $pengumuman->id }}">{{ $pengumuman->judul }}</a></td>
                            <td>{{ substr(strip_tags($pengumuman->isi), 0, 100)."...." }}</td>
                        </tr>
                        <div class="modal fade" id="detailPengumuman{{ $pengumuman->id }}">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content bg-default">
                                    <div class="modal-header">
                                        <h4 class="modal-title">{{ $pengumuman->judul }}</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>{!! $pengumuman->isi !!}</p>
                                    </div>
                                    <div class="modal-footer justify-content-between">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </tbody>
                </table>
            </div>                            
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card card-outline">
            <div class="card-header">
            <h3 class="card-title"><i class="fas fa-hand-holding-usd mr-1"></i>Keuangan Gereja Tahun {{ $year }}</h3>
                <div class="card-tools"></div>
            </div><!-- /.card-header -->
            <div class="card-body table-responsive" style="height: 322px;">
                <canvas id="keuangan-chart" height="300" style="height: 300px;"></canvas>
            </div><!-- /.card-body -->
        </div>
    </div>
</div>
@endsection

@section('javascript')
<!-- ChartJS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    var areaChartData = {
      labels  : ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'],
      datasets: [
        {
          label               : 'Total Saldo Bulanan (Rp)',
          backgroundColor     : 'rgba(60,141,188,0.9)',
          borderColor         : 'rgba(60,141,188,0.8)',
          pointRadius          : false,
          pointColor          : '#3b8bba',
          pointStrokeColor    : 'rgba(60,141,188,1)',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(60,141,188,1)',
          data                : {{ json_encode($datachart) }}
        }
      ]
    }
    $.widget.bridge('uibutton', $.ui.button)

    var barChartCanvas = $('#keuangan-chart').get(0).getContext('2d')
    var barChartData = jQuery.extend(true, {}, areaChartData)
    var temp0 = areaChartData.datasets[0]
    barChartData.datasets[0] = temp0

    var barChartOptions = {
      responsive              : true,
      maintainAspectRatio     : false,
      datasetFill             : false
    }

    var barChart = new Chart(barChartCanvas, {
      type: 'bar', 
      data: barChartData,
      options: barChartOptions
    })
</script>
@endsection

resources/views/welcome1.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Sistem Informasi Gereja
                </div>
            </div>
        </div>
    </body>
</html>