routes/web.php
    Route::get('', ['as' => 'index', 'uses' => 'SidiController@index'])->middleware('permission:read sidi');
    Route::post('', ['as' => 'store', 'uses' => 'SidiController@store'])->middleware('permission:create sidi');
    Route::get('/create', ['as' => 'create', 'uses' => 'SidiController@create'])->middleware('permission:create sidi');
    Route::get('/{sidi}', ['as' => 'show', 'uses' => 'SidiController@show'])->middleware('permission:read sidi');
    Route::put('/{sidi}', ['as' => 'update', 'uses' => 'SidiController@update'])->middleware('permission:update sidi');
    Route::delete('/{sidi}', ['as' => 'destroy', 'uses' => 'SidiController@destroy'])->middleware('permission:delete sidi');
    Route::get('/{sidi}/edit', ['as' => 'edit', 'uses' => 'SidiController@edit'])->middleware('permission:update sidi');
});

Route::group(['prefix'=>'nikah','as'=>'nikah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'NikahController@index'])->middleware('permission:read nikah');
    Route::post('', ['as' => 'store', 'uses' => 'NikahController@store'])->middleware('permission:create nikah');
    Route::get('/create', ['as' => 'create', 'uses' => 'NikahController@create'])->middleware('permission:create nikah');
    Route::get('/{nikah}', ['as' => 'show', 'uses' => 'NikahController@show'])->middleware('permission:read nikah');
    Route::put('/{nikah}', ['as' => 'update', 'uses' => 'NikahController@update'])->middleware('permission:update nikah');
    Route::delete('/{nikah}', ['as' => 'destroy', 'uses' => 'NikahController@destroy'])->middleware('permission:delete nikah');
    Route::get('/{nikah}/edit', ['as' => 'edit', 'uses' => 'NikahController@edit'])->middleware('permission:update nikah');
});

Route::group(['prefix'=>'pengumuman','as'=>'pengumuman.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'PengumumanController@index'])->middleware('permission:read pengumuman');
    Route::post('', ['as' => 'store', 'uses' => 'PengumumanController@store'])->middleware('permission:create pengumuman');
    Route::get('/create', ['as' => 'create', 'uses' => 'PengumumanController@create'])->middleware('permission:create pengumuman');
    Route::get('/{pengumuman}', ['as' => 'show', 'uses' => 'PengumumanController@show'])->middleware('permission:read pengumuman');
    Route::put('/{pengumuman}', ['as' => 'update', 'uses' => 'PengumumanController@update'])->middleware('permission:update pengumuman');
    Route::delete('/{pengumuman}', ['as' => 'destroy', 'uses' => 'PengumumanController@destroy'])->middleware('permission:delete pengumuman');
    Route::get('/{pengumuman}/edit', ['as' => 'edit', 'uses' => 'PengumumanController@edit'])->middleware('permission:update pengumuman');
});

Route::group(['prefix'=>'ibadah','as'=>'ibadah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'IbadahController@index'])->middleware('permission:read ibadah');
    Route::post('', ['as' => 'store', 'uses' => 'IbadahController@store'])->middleware('permission:create ibadah');
    Route::get('/create', ['as' => 'create', 'uses' => 'IbadahController@create'])->middleware('permission:create ibadah');
    Route::get('/{ibadah}', ['as' => 'show', 'uses' => 'IbadahController@show'])->middleware('permission:read ibadah');
    Route::put('/{ibadah}', ['as' => 'update', 'uses' => 'IbadahController@update'])->middleware('permission:update ibadah');
    Route::delete('/{ibadah}', ['as' => 'destroy', 'uses' => 'IbadahController@destroy'])->middleware('permission:delete ibadah');
    Route::get('/{ibadah}/edit', ['as' => 'edit', 'uses' => 'IbadahController@edit'])->middleware('permission:update ibadah');
});

Route::group(['prefix'=>'keuangan','as'=>'keuangan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'KeuanganController@index'])->middleware('permission:read keuangan');
    Route::post('', ['as' => 'store', 'uses' => 'KeuanganController@store'])->middleware('permission:create keuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'KeuanganController@create'])->middleware('permission:create keuangan');
    Route::get('/{keuangan}', ['as' => 'show', 'uses' => 'KeuanganController@show'])->middleware('permission:read keuangan');
    Route::put('/{keuangan}', ['as' => 'update', 'uses' => 'KeuanganController@update'])->middleware('permission:update keuangan');
    Route::delete('/{keuangan}', ['as' => 'destroy', 'uses' => 'KeuanganController@destroy'])->middleware('permission:delete keuangan');
    Route::get('/{keuangan}/edit', ['as' => 'edit', 'uses' => 'KeuanganController@edit'])->middleware('permission:update keuangan');
    Route::post('/getData', ['as' => 'getData', 'uses' => 'KeuanganController@getDaftarKeuangan']);
    Route::post('/getTable', ['as' => 'getTable', 'uses' => 'KeuanganController@getTable']);
});

Route::group(['prefix'=>'keuangankeluar','as'=>'keuangankeluar.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'KeuanganController@index_keluar'])->middleware('permission:read keuangan');
    Route::post('', ['as' => 'store', 'uses' => 'KeuanganController@store'])->middleware('permission:create keuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'KeuanganController@create_keluar'])->middleware('permission:create keuangan');
    Route::get('/{keuangan}', ['as' => 'show', 'uses' => 'KeuanganController@show'])->middleware('permission:read keuangan');
    Route::put('/{keuangan}', ['as' => 'update', 'uses' => 'KeuanganController@update'])->middleware('permission:update keuangan');
    Route::delete('/{keuangan}', ['as' => 'destroy', 'uses' => 'KeuanganController@destroy_keluar'])->middleware('permission:delete keuangan');
    Route::get('/{keuangan}/edit', ['as' => 'edit', 'uses' => 'KeuanganController@edit_keluar'])->middleware('permission:update keuangan');
    Route::post('/getData', ['as' => 'getData', 'uses' => 'KeuanganController@getDaftarKeuangan']);
    Route::post('/getTable', ['as' => 'getTable', 'uses' => 'KeuanganController@getTableKeluar']);
});

Route::group(['prefix'=>'lapkeuangan','as'=>'lapkeuangan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'LapKeuanganController@index']);
    Route::post('/getTable', ['as' => 'getTable', 'uses' => 'LapKeuanganController@getTable']);
    Route::post('/getSaldo', ['as' => 'getSaldo', 'uses' => 'LapKeuanganController@getSaldo']);
    Route::post('/getJumlah', ['as' => 'getJumlah', 'uses' => 'LapKeuanganController@getJumlah']);
    Route::post('/export', ['as' => 'export', 'uses' => 'LapKeuanganController@export_excel']);
});

Route::group(['prefix'=>'setmajelis','as'=>'setmajelis.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SetMajelisController@index'])->middleware('permission:read setmajelis');
    Route::post('', ['as' => 'store', 'uses' => 'SetMajelisController@store'])->middleware('permission:create setmajelis');
    Route::get('/create', ['as' => 'create', 'uses' => 'SetMajelisController@create'])->middleware('permission:create setmajelis');
    Route::get('/{setMajelis}', ['as' => 'show', 'uses' => 'SetMajelisController@show'])->middleware('permission:read setmajelis');
    Route::put('/{setMajelis}', ['as' => 'update', 'uses' => 'SetMajelisController@update'])->middleware('permission:update setmajelis');
    Route::delete('/{setMajelis}', ['as' => 'destroy', 'uses' => 'SetMajelisController@destroy'])->middleware('permission:delete setmajelis');
    Route::get('/{setMajelis}/edit', ['as' => 'edit', 'uses' => 'SetMajelisController@edit'])->middleware('permission:update setmajelis');
});

Route::group(['prefix'=>'setkegiatan','as'=>'setkegiatan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SetKegiatanController@index'])->middleware('permission:read setkegiatan');
    Route::post('', ['as' => 'store', 'uses' => 'SetKegiatanController@store'])->middleware('permission:create setkegiatan');
    Route::get('/create', ['as' => 'create', 'uses' => 'SetKegiatanController@create'])->middleware('permission:create setkegiatan');
    Route::get('/{setKegiatan}', ['as' => 'show', 'uses' => 'SetKegiatanController@show'])->middleware('permission:read setkegiatan');
    Route::put('/{setKegiatan}', ['as' => 'update', 'uses' => 'SetKegiatanController@update'])->middleware('permission:update setkegiatan');
    Route::post('/{setKegiatan}', ['as' => 'fotoup', 'uses' => 'SetKegiatanController@uploadFoto']);
    Route::delete('/{setKegiatan}', ['as' => 'destroy', 'uses' => 'SetKegiatanController@destroy'])->middleware('permission:delete setkegiatan');
    Route::get('/{setKegiatan}/edit', ['as' => 'edit', 'uses' => 'SetKegiatanController@edit'])->middleware('permission:update setkegiatan');
});

Route::group(['prefix'=>'setrenungan','as'=>'setrenungan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'RenunganController@index']);
    Route::post('', ['as' => 'store', 'uses' => 'RenunganController@store']);
    Route::get('/create', ['as' => 'create', 'uses' => 'RenunganController@create']);
    Route::get('/{renungan}', ['as' => 'show', 'uses' => 'RenunganController@show']);
    Route::put('/{renungan}', ['as' => 'update', 'uses' => 'RenunganController@update']);
    Route::delete('/{renungan}', ['as' => 'destroy', 'uses' => 'RenunganController@destroy']);
    Route::get('/{renungan}/edit', ['as' => 'edit', 'uses' => 'RenunganController@edit']);
});

Route::group(['prefix'=>'setsejarah','as'=>'setsejarah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SetSejarahController@index']);
    Route::post('', ['as' => 'store', 'uses' => 'SetSejarahController@store']);
    Route::get('/create', ['as' => 'create', 'uses' => 'SetSejarahController@create']);
    Route::get('/{setSejarah}', ['as' => 'show', 'uses' => 'SetSejarahController@show']);
    Route::put('/{setSejarah}', ['as' => 'update', 'uses' => 'SetSejarahController@update']);
    Route::delete('/{setSejarah}', ['as' => 'destroy', 'uses' => 'SetSejarahController@destroy']);

app/SetKegiatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SetKegiatan extends Model
{
    protected $table = 'front_kegiatan';

    protected $guarded = [];

    public $timestamps = true;
}

app/Http/Controllers/SetKegiatanController.php
<?php

namespace App\Http\Controllers;

use App\SetKegiatan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class SetKegiatanController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kegiatans = SetKegiatan::orderBy('id', 'desc')->get();
        return view('setkegiatan.list', compact('kegiatans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('setkegiatan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_kegiatan' => 'required',
            'file' => 'required',
        ]);

        if($request->file('file')){
			$file = $request->file('file');
			$namefile = "kegiatan-".time().".".$file->getClientOriginalExtension();
			$request->merge(["foto_kegiatan" => $namefile]);
			$file->move("img/kegiatan", $namefile);
		}

        SetKegiatan::create($request->except('file'));

        return redirect()->route('setkegiatan.index')
                        ->with('success','Kegiatan berhasil ditambah.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SetKegiatan  $setKegiatan
     * @return \Illuminate\Http\Response
     */
    public function show(SetKegiatan $setKegiatan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SetKegiatan  $setKegiatan
     * @return \Illuminate\Http\Response
     */
    public function edit(SetKegiatan $setKegiatan)
    {
        return view('setkegiatan.edit',compact('setKegiatan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SetKegiatan  $setKegiatan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SetKegiatan $setKegiatan)
    {
        $request->validate([
            'nama_kegiatan' => 'required',
        ]);

        $setKegiatan->update($request->except('files'));

        return redirect()->route('setkegiatan.index')
                        ->with('success','Kegiatan berhasil diubah.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SetKegiatan  $setKegiatan
     * @return \Illuminate\Http\Response
     */
    public function destroy(SetKegiatan $setKegiatan)
    {
        if(File::exists(public_path("img/kegiatan/".$setKegiatan->foto_kegiatan))){
            File::delete(public_path("img/kegiatan/".$setKegiatan->foto_kegiatan));
        }
        $setKegiatan->delete();

        return redirect()->route('setkegiatan.index')
                        ->with('success','Kegiatan berhasil dihapus.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Jemaat  $jemaat
     * @return \Illuminate\Http\Response
     */
    public function uploadFoto(Request $request, SetKegiatan $setKegiatan)
    {
        if($request->file('file')){
            if(File::exists(public_path("img/kegiatan/".$request->input('foto_kegiatan')))){
                File::delete(public_path("img/kegiatan/".$request->input('foto_kegiatan')));
            }
			$file = $request->file('file');
			$namefile = "kegiatan-".time().".".$file->getClientOriginalExtension();
			$request->merge(["foto_kegiatan" => $namefile]);
			$file->move("img/kegiatan", $namefile);
            $setKegiatan->update($request->except(['file']));
		}
        return redirect()->route('setkegiatan.edit',$setKegiatan->id);
    }
}

resources/views/setKegiatan/create.blade.php
@extends('layouts.base')

@section('css')
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
@endsection

@section('title_head')
    Tambah Data Kegiatan
@endsection

@section('bread')
    <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('setkegiatan.index') }}">Setting Kegiatan</a></li>
    <li class="breadcrumb-item active">Tambah Data Kegiatan</li>
@endsection

@section('content')
<form action="{{ route('setkegiatan.store') }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Data Kegiatan</h3>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label for="nama_kegiatan" class="col-sm-3 col-form-label">Nama Kegiatan</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="nama_kegiatan" name="nama_kegiatan" placeholder="Nama Kegiatan">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="file" class="col-sm-3 col-form-label">Foto Kegiatan</label>
                        <div class="col-sm-5">
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="file" name="file">
                                    <label class="custom-file-label" for="file">Choose file</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="ket_kegiatan" class="col-sm-3 col-form-label">Keterangan Kegiatan</label>
                        <div class="col-sm-8">
                            <textarea class="ketkegiatan" id="ket_kegiatan" name="ket_kegiatan"></textarea>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{ route('setkegiatan.index') }}" class="btn btn-default float-right">Batal</a>
                </div>
            </div>
        </div>
    </div>

</form>
@endsection

@section('javascript')
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<!-- InputMask -->
<script src="{{ asset('plugins/inputmask/min/jquery.inputmask.bundle.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<!-- date-range-picker -->
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- bs-custom-file-input -->
<script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<script>
    $(function(){
        bsCustomFileInput.init();
        $('.datepick').datetimepicker({
            format: 'L'
        });
        $('[data-mask]').inputmask();
        $('.select2').select2({
            theme: 'bootstrap4'
        });
        // Summernote
        $('.ketkegiatan').summernote({
            placeholder: 'Keterangan Kegiatan',
            height:200,
            tabDisable: true,
            disableDragAndDrop: true,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph', 'height']],
                ['table', ['table']],
                ['insert', ['link']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ],
        })
    });
</script>
@endsection

resources/views/setKegiatan/edit.blade.php
@extends('layouts.base')

@section('css')
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
@endsection

@section('title_head')
    Ubah Data Kegiatan
@endsection

@section('bread')
    <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('setkegiatan.index') }}">Setting Kegiatan</a></li>
    <li class="breadcrumb-item active">Ubah Data Kegiatan</li>
@endsection

@section('content')
<form action="{{ route('setkegiatan.update', $setKegiatan->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Ubah Data Majelis</h3>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label for="nama_kegiatan" class="col-sm-3 col-form-label">Nama Kegiatan</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="nama_kegiatan" name="nama_kegiatan" placeholder="Nama Kegiatan" value="{{ $setKegiatan->nama_kegiatan }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Foto Kegiatan</label>
                        <div class="col-sm-5"><img src="{{ asset('img/kegiatan/'. $setKegiatan->foto_kegiatan) }}" class="img-fluid" alt=""></div>
                        <div class="col-sm-3"><button type="button" class="btn btn-default" data-toggle="modal" data-target="#uploadModal">Ubah Foto</button></div>
                    </div>
                    <div class="form-group row">
                        <label for="ket_kegiatan" class="col-sm-3 col-form-label">Keterangan Kegiatan</label>
                        <div class="col-sm-8">
                            <textarea class="ketkegiatan" id="ket_kegiatan" name="ket_kegiatan">{{ $setKegiatan->ket_kegiatan }}</textarea>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{ route('setkegiatan.index') }}" class="btn btn-default float-right">Batal</a>
                </div>
            </div>
        </div>
    </div>
</form>

<form action="{{ route('setkegiatan.fotoup',$setKegiatan->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="modal fade" id="uploadModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Unggah Foto</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" class="custom-file-input" name="foto_kegiatan" value="{{ $setKegiatan->foto_kegiatan }}">
                    <div class="form-group">
                        <label for="file">Foto Kegiatan</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="file" name="file">
                                <label class="custom-file-label" for="file">Choose file</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Upload</button>
                    
                </div>
            </div>
        </div>
    </div>
    </form>
@endsection

@section('javascript')
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<!-- InputMask -->
<script src="{{ asset('plugins/inputmask/min/jquery.inputmask.bundle.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<!-- date-range-picker -->
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- bs-custom-file-input -->
<script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<script>
    $(function(){
        bsCustomFileInput.init();
        $('.datepick').datetimepicker({
            format: 'L'
        });
        $('[data-mask]').inputmask();
        $('.select2').select2({
            theme: 'bootstrap4'
        });
        // Summernote
        $('.ketkegiatan').summernote({
            placeholder: 'Keterangan Kegiatan',
            height:200,
            tabDisable: true,
            disableDragAndDrop: true,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'italic', 'underline', 'clear']],
                ['fontname', ['fontname']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph', 'height']],
                ['table', ['table']],
                ['insert', ['link']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ],
        })
    });
</script>
@endsection