routes/web.php
    Route::get('', ['as' => 'index', 'uses' => 'SidiController@index'])->middleware('permission:read sidi');
    Route::post('', ['as' => 'store', 'uses' => 'SidiController@store'])->middleware('permission:create sidi');
    Route::get('/create', ['as' => 'create', 'uses' => 'SidiController@create'])->middleware('permission:create sidi');
    Route::get('/{sidi}', ['as' => 'show', 'uses' => 'SidiController@show'])->middleware('permission:read sidi');
    Route::put('/{sidi}', ['as' => 'update', 'uses' => 'SidiController@update'])->middleware('permission:update sidi');
    Route::delete('/{sidi}', ['as' => 'destroy', 'uses' => 'SidiController@destroy'])->middleware('permission:delete sidi');
    Route::get('/{sidi}/edit', ['as' => 'edit', 'uses' => 'SidiController@edit'])->middleware('permission:update sidi');
});

Route::group(['prefix'=>'nikah','as'=>'nikah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'NikahController@index'])->middleware('permission:read nikah');
    Route::post('', ['as' => 'store', 'uses' => 'NikahController@store'])->middleware('permission:create nikah');
    Route::get('/create', ['as' => 'create', 'uses' => 'NikahController@create'])->middleware('permission:create nikah');
    Route::get('/{nikah}', ['as' => 'show', 'uses' => 'NikahController@show'])->middleware('permission:read nikah');
    Route::put('/{nikah}', ['as' => 'update', 'uses' => 'NikahController@update'])->middleware('permission:update nikah');
    Route::delete('/{nikah}', ['as' => 'destroy', 'uses' => 'NikahController@destroy'])->middleware('permission:delete nikah');
    Route::get('/{nikah}/edit', ['as' => 'edit', 'uses' => 'NikahController@edit'])->middleware('permission:update nikah');
});

Route::group(['prefix'=>'pengumuman','as'=>'pengumuman.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'PengumumanController@index'])->middleware('permission:read pengumuman');
    Route::post('', ['as' => 'store', 'uses' => 'PengumumanController@store'])->middleware('permission:create pengumuman');
    Route::get('/create', ['as' => 'create', 'uses' => 'PengumumanController@create'])->middleware('permission:create pengumuman');
    Route::get('/{pengumuman}', ['as' => 'show', 'uses' => 'PengumumanController@show'])->middleware('permission:read pengumuman');
    Route::put('/{pengumuman}', ['as' => 'update', 'uses' => 'PengumumanController@update'])->middleware('permission:update pengumuman');
    Route::delete('/{pengumuman}', ['as' => 'destroy', 'uses' => 'PengumumanController@destroy'])->middleware('permission:delete pengumuman');
    Route::get('/{pengumuman}/edit', ['as' => 'edit', 'uses' => 'PengumumanController@edit'])->middleware('permission:update pengumuman');
});

Route::group(['prefix'=>'ibadah','as'=>'ibadah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'IbadahController@index'])->middleware('permission:read ibadah');
    Route::post('', ['as' => 'store', 'uses' => 'IbadahController@store'])->middleware('permission:create ibadah');
    Route::get('/create', ['as' => 'create', 'uses' => 'IbadahController@create'])->middleware('permission:create ibadah');
    Route::get('/{ibadah}', ['as' => 'show', 'uses' => 'IbadahController@show'])->middleware('permission:read ibadah');
    Route::put('/{ibadah}', ['as' => 'update', 'uses' => 'IbadahController@update'])->middleware('permission:update ibadah');
    Route::delete('/{ibadah}', ['as' => 'destroy', 'uses' => 'IbadahController@destroy'])->middleware('permission:delete ibadah');
    Route::get('/{ibadah}/edit', ['as' => 'edit', 'uses' => 'IbadahController@edit'])->middleware('permission:update ibadah');
});

Route::group(['prefix'=>'keuangan','as'=>'keuangan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'KeuanganController@index'])->middleware('permission:read keuangan');
    Route::post('', ['as' => 'store', 'uses' => 'KeuanganController@store'])->middleware('permission:create keuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'KeuanganController@create'])->middleware('permission:create keuangan');
    Route::get('/{keuangan}', ['as' => 'show', 'uses' => 'KeuanganController@show'])->middleware('permission:read keuangan');
    Route::put('/{keuangan}', ['as' => 'update', 'uses' => 'KeuanganController@update'])->middleware('permission:update keuangan');
    Route::delete('/{keuangan}', ['as' => 'destroy', 'uses' => 'KeuanganController@destroy'])->middleware('permission:delete keuangan');
    Route::get('/{keuangan}/edit', ['as' => 'edit', 'uses' => 'KeuanganController@edit'])->middleware('permission:update keuangan');
    Route::post('/getData', ['as' => 'getData', 'uses' => 'KeuanganController@getDaftarKeuangan']);
    Route::post('/getTable', ['as' => 'getTable', 'uses' => 'KeuanganController@getTable']);
});

Route::group(['prefix'=>'keuangankeluar','as'=>'keuangankeluar.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'KeuanganController@index_keluar'])->middleware('permission:read keuangan');
    Route::post('', ['as' => 'store', 'uses' => 'KeuanganController@store'])->middleware('permission:create keuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'KeuanganController@create_keluar'])->middleware('permission:create keuangan');
    Route::get('/{keuangan}', ['as' => 'show', 'uses' => 'KeuanganController@show'])->middleware('permission:read keuangan');
    Route::put('/{keuangan}', ['as' => 'update', 'uses' => 'KeuanganController@update'])->middleware('permission:update keuangan');
    Route::delete('/{keuangan}', ['as' => 'destroy', 'uses' => 'KeuanganController@destroy_keluar'])->middleware('permission:delete keuangan');
    Route::get('/{keuangan}/edit', ['as' => 'edit', 'uses' => 'KeuanganController@edit_keluar'])->middleware('permission:update keuangan');
    Route::post('/getData', ['as' => 'getData', 'uses' => 'KeuanganController@getDaftarKeuangan']);
    Route::post('/getTable', ['as' => 'getTable', 'uses' => 'KeuanganController@getTableKeluar']);
});

Route::group(['prefix'=>'lapkeuangan','as'=>'lapkeuangan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'LapKeuanganController@index']);
    Route::post('/getTable', ['as' => 'getTable', 'uses' => 'LapKeuanganController@getTable']);
    Route::post('/getSaldo', ['as' => 'getSaldo', 'uses' => 'LapKeuanganController@getSaldo']);
    Route::post('/getJumlah', ['as' => 'getJumlah', 'uses' => 'LapKeuanganController@getJumlah']);
    Route::post('/export', ['as' => 'export', 'uses' => 'LapKeuanganController@export_excel']);
});

Route::group(['prefix'=>'setmajelis','as'=>'setmajelis.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SetMajelisController@index'])->middleware('permission:read setmajelis');
    Route::post('', ['as' => 'store', 'uses' => 'SetMajelisController@store'])->middleware('permission:create setmajelis');
    Route::get('/create', ['as' => 'create', 'uses' => 'SetMajelisController@create'])->middleware('permission:create setmajelis');
    Route::get('/{setMajelis}', ['as' => 'show', 'uses' => 'SetMajelisController@show'])->middleware('permission:read setmajelis');
    Route::put('/{setMajelis}', ['as' => 'update', 'uses' => 'SetMajelisController@update'])->middleware('permission:update setmajelis');
    Route::delete('/{setMajelis}', ['as' => 'destroy', 'uses' => 'SetMajelisController@destroy'])->middleware('permission:delete setmajelis');
    Route::get('/{setMajelis}/edit', ['as' => 'edit', 'uses' => 'SetMajelisController@edit'])->middleware('permission:update setmajelis');
});

Route::group(['prefix'=>'setkegiatan','as'=>'setkegiatan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SetKegiatanController@index'])->middleware('permission:read setkegiatan');
    Route::post('', ['as' => 'store', 'uses' => 'SetKegiatanController@store'])->middleware('permission:create setkegiatan');
    Route::get('/create', ['as' => 'create', 'uses' => 'SetKegiatanController@create'])->middleware('permission:create setkegiatan');
    Route::get('/{setKegiatan}', ['as' => 'show', 'uses' => 'SetKegiatanController@show'])->middleware('permission:read setkegiatan');
    Route::put('/{setKegiatan}', ['as' => 'update', 'uses' => 'SetKegiatanController@update'])->middleware('permission:update setkegiatan');
    Route::post('/{setKegiatan}', ['as' => 'fotoup', 'uses' => 'SetKegiatanController@uploadFoto']);
    Route::delete('/{setKegiatan}', ['as' => 'destroy', 'uses' => 'SetKegiatanController@destroy'])->middleware('permission:delete setkegiatan');
    Route::get('/{setKegiatan}/edit', ['as' => 'edit', 'uses' => 'SetKegiatanController@edit'])->middleware('permission:update setkegiatan');
});

Route::group(['prefix'=>'setrenungan','as'=>'setrenungan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'RenunganController@index']);
    Route::post('', ['as' => 'store', 'uses' => 'RenunganController@store']);
    Route::get('/create', ['as' => 'create', 'uses' => 'RenunganController@create']);
    Route::get('/{renungan}', ['as' => 'show', 'uses' => 'RenunganController@show']);
    Route::put('/{renungan}', ['as' => 'update', 'uses' => 'RenunganController@update']);
    Route::delete('/{renungan}', ['as' => 'destroy', 'uses' => 'RenunganController@destroy']);
    Route::get('/{renungan}/edit', ['as' => 'edit', 'uses' => 'RenunganController@edit']);
});

Route::group(['prefix'=>'setsejarah','as'=>'setsejarah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SetSejarahController@index']);
    Route::post('', ['as' => 'store', 'uses' => 'SetSejarahController@store']);
    Route::get('/create', ['as' => 'create', 'uses' => 'SetSejarahController@create']);
    Route::get('/{setSejarah}', ['as' => 'show', 'uses' => 'SetSejarahController@show']);
    Route::put('/{setSejarah}', ['as' => 'update', 'uses' => 'SetSejarahController@update']);
    Route::delete('/{setSejarah}', ['as' => 'destroy', 'uses' => 'SetSejarahController@destroy']);

resources/views/lapkeuangan/list.blade.php
@extends('layouts.base')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

@section('title_head')
    Laporan Keuangan Gereja
@endsection

@section('bread')
    <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
    <li class="breadcrumb-item active">Laporan Keuangan Gereja</li>
@endsection

@section('content')
<?php
    $bulans = array('Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember');
    $bulan_sekarang = date("m");
    $tahun_sekarang = date("Y");
    $saldo = 0;
?>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Data Laporan Keuangan Gereja</h3>
                <div class="card-tools">

                </div>
            </div>
            <div class="card-body">
                <form class="form-horizontal" action="{{ route('lapkeuangan.export') }}" method="POST">
                    @csrf
                    <div class="form-group row">
                        <label for="tahun" class="col-sm-1 col-form-label">Tahun</label>
                        <div class="col-sm-2">
                            <select class="form-control select2" name="tahun" id="tahun">
                                @for ($i = 2018; $i < 3030; $i++)
                                <option value="{{ $i }}" @if ($i == $tahun_sekarang) selected @endif>{{ $i }}</option>
                                @endfor
                            </select>
                        </div>
                        <label for="bulan" class="col-sm-1 col-form-label">Bulan</label>
                        <div class="col-sm-2">
                            <select class="form-control select2" name="bulan" id="bulan">
                                <option value="all" selected>Semua Bulan</option>
                                @foreach($bulans as $key => $val)
                                <option value="{{ $key+1 }}">{{ $val }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-sm-2 offset-sm-4">
                            <button class="form-control btn btn-success pull-right" id="export">EXPORT EXCEL</button>
                            {{-- <a href="/lapkeuangan/export" class="form-control btn btn-success pull-right" target="_blank">EXPORT EXCEL</a> --}}
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-body table-responsive p-0" style="height: 500px;">
                <table class="table table-bordered table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th style="width: 15%">Tgl Pencatatan</th>
                            <th>Keterangan</th>
                            <th style="width: 15%">Kredit (Rp)</th>
                            <th style="width: 15%">Debit (Rp)</th>
                        </tr>
                    </thead>
                    <tbody id="setTable">

                    </tbody>
                    <tfoot id="setJumlah">
                        
                    </tfoot>
                </table>
            </div>
            <div class="card-body">
                <div class="col-6 offset-6">
                    <p class="lead"></p>
                    <div class="table-responsive">
                        <table class="table">
                            <tbody id="setSaldo">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('javascript')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>

<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<!-- InputMask -->
<script src="{{ asset('plugins/inputmask/min/jquery.inputmask.bundle.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<!-- date-range-picker -->
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<script>
    $(function(){
        var thn = $('#tahun').val();
        var bln = $('#bulan').val();
        $.ajax({
            type:"POST",
            dataType:"html",
            url:"{{ route('lapkeuangan.getTable') }}",
            data:{
                _token:'{{ csrf_token() }}',
                tahun:thn,
                bulan:bln
            },
            success: function(data) {
                $('#setTable').html(data);
            }
        });
        $.ajax({
            type:"POST",
            dataType:"html",
            url:"{{ route('lapkeuangan.getSaldo') }}",
            data:{
                _token:'{{ csrf_token() }}',
                tahun:thn,
                bulan:bln
            },
            success: function(data) {
                $('#setSaldo').html(data);
            }
        });
        $.ajax({
            type:"POST",
            dataType:"html",
            url:"{{ route('lapkeuangan.getJumlah') }}",
            data:{
                _token:'{{ csrf_token() }}',
                tahun:thn,
                bulan:bln
            },
            success: function(data) {
                $('#setJumlah').html(data);
            }
        });
        $('#tahun').change(function() {
            var thn = $('#tahun').val();
            var bln = $('#bulan').val();
            $.ajax({
                type:"POST",
                dataType:"html",
                url:"{{ route('lapkeuangan.getTable') }}",
                data:{
                    _token:'{{ csrf_token() }}',
                    tahun:thn,
                    bulan:bln
                },
                success: function(data) {
                    $('#setTable').html(data);
                }
            });
            $.ajax({
                type:"POST",
                dataType:"html",
                url:"{{ route('lapkeuangan.getSaldo') }}",
                data:{
                    _token:'{{ csrf_token() }}',
                    tahun:thn,
                    bulan:bln
                },
                success: function(data) {
                    $('#setSaldo').html(data);
                }
            });
            $.ajax({
                type:"POST",
                dataType:"html",
                url:"{{ route('lapkeuangan.getJumlah') }}",
                data:{
                    _token:'{{ csrf_token() }}',
                    tahun:thn,
                    bulan:bln
                },
                success: function(data) {
                    $('#setJumlah').html(data);
                }
            });
        });
        $('#bulan').change(function() {
            var thn = $('#tahun').val();
            var bln = $('#bulan').val();
            $.ajax({
                type:"POST",
                dataType:"html",
                url:"{{ route('lapkeuangan.getTable') }}",
                data:{
                    _token:'{{ csrf_token() }}',
                    tahun:thn,
                    bulan:bln
                },
                success: function(data) {
                    $('#setTable').html(data);
                }
            });
            $.ajax({
                type:"POST",
                dataType:"html",
                url:"{{ route('lapkeuangan.getSaldo') }}",
                data:{
                    _token:'{{ csrf_token() }}',
                    tahun:thn,
                    bulan:bln
                },
                success: function(data) {
                    $('#setSaldo').html(data);
                }
            });
            $.ajax({
                type:"POST",
                dataType:"html",
                url:"{{ route('lapkeuangan.getJumlah') }}",
                data:{
                    _token:'{{ csrf_token() }}',
                    tahun:thn,
                    bulan:bln
                },
                success: function(data) {
                    $('#setJumlah').html(data);
                }
            });
        });
        $('.datepick').datetimepicker({
            format: 'L'
        });
        $('[data-mask]').inputmask();
        $('.select2').select2({
            theme: 'bootstrap4'
        });
        $(".datatabel").DataTable({
            "ordering": false,
        });
    });
</script>
@endsection