routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'changeprofile', 'as' => 'changeprofile.'], function () {
    Route::put('', ['as' => 'update', 'uses' => 'HomeController@updatepropfile']);
    Route::get('/edit', ['as' => 'edit', 'uses' => 'HomeController@editprofile']);
    Route::post('', ['as' => 'fotoup', 'uses' => 'HomeController@uploadFoto']);
});

Route::group(['prefix' => 'changepassword', 'as' => 'changepassword.'], function () {
    Route::post('', ['as' => 'update', 'uses' => 'HomeController@updatepassword']);
    Route::get('/edit', ['as' => 'edit', 'uses' => 'HomeController@editpassword']);
});

Route::group(['prefix' => 'jabatan', 'as' => 'jabatan.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'JabatanController@index']);
    Route::post('', ['as' => 'store', 'uses' => 'JabatanController@store']);
    Route::get('/create', ['as' => 'create', 'uses' => 'JabatanController@create']);
    Route::get('/{jabatan}', ['as' => 'show', 'uses' => 'JabatanController@show']);
    Route::put('/{jabatan}', ['as' => 'update', 'uses' => 'JabatanController@update']);
    Route::delete('/{jabatan}', ['as' => 'destroy', 'uses' => 'JabatanController@destroy']);
    Route::get('/{jabatan}/edit', ['as' => 'edit', 'uses' => 'JabatanController@edit']);
});

Route::group(['prefix' => 'kategori', 'as' => 'kategori.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'KatIbadahController@index'])->middleware('permission:read katibadah');
    Route::post('', ['as' => 'store', 'uses' => 'KatIbadahController@store'])->middleware('permission:create katibadah');
    Route::get('/create', ['as' => 'create', 'uses' => 'KatIbadahController@create'])->middleware('permission:create katibadah');
    Route::get('/{kategori}', ['as' => 'show', 'uses' => 'KatIbadahController@show'])->middleware('permission:read katibadah');
    Route::put('/{kategori}', ['as' => 'update', 'uses' => 'KatIbadahController@update'])->middleware('permission:update katibadah');
    Route::delete('/{kategori}', ['as' => 'destroy', 'uses' => 'KatIbadahController@destroy'])->middleware('permission:delete katibadah');
    Route::get('/{kategori}/edit', ['as' => 'edit', 'uses' => 'KatIbadahController@edit'])->middleware('permission:update katibadah');
});

Route::group(['prefix' => 'setKeuangan', 'as' => 'setKeuangan.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'SetKeuanganController@index'])->middleware('permission:read setkeuangan');
    Route::post('', ['as' => 'store', 'uses' => 'SetKeuanganController@store'])->middleware('permission:create setkeuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'SetKeuanganController@create'])->middleware('permission:create setkeuangan');
    Route::get('/{setKeuangan}', ['as' => 'show', 'uses' => 'SetKeuanganController@show'])->middleware('permission:read setkeuangan');
    Route::put('/{setKeuangan}', ['as' => 'update', 'uses' => 'SetKeuanganController@update'])->middleware('permission:update setkeuangan');
    Route::delete('/{setKeuangan}', ['as' => 'destroy', 'uses' => 'SetKeuanganController@destroy'])->middleware('permission:delete setkeuangan');
    Route::get('/{setKeuangan}/edit', ['as' => 'edit', 'uses' => 'SetKeuanganController@edit'])->middleware('permission:update setkeuangan');
});

Route::group(['prefix'=>'jemaat','as'=>'jemaat.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'JemaatController@index'])->middleware('permission:read jemaat');
    Route::post('', ['as' => 'store', 'uses' => 'JemaatController@store'])->middleware('permission:create jemaat');
    Route::get('/create', ['as' => 'create', 'uses' => 'JemaatController@create'])->middleware('permission:create jemaat');
    Route::get('/{jemaat}', ['as' => 'show', 'uses' => 'JemaatController@show'])->middleware('permission:read jemaat');
    Route::put('/{jemaat}', ['as' => 'update', 'uses' => 'JemaatController@update'])->middleware('permission:update jemaat');
    Route::post('/{jemaat}', ['as' => 'fotoup', 'uses' => 'JemaatController@uploadFoto']);
    Route::delete('/{jemaat}', ['as' => 'destroy', 'uses' => 'JemaatController@destroy'])->middleware('permission:delete jemaat');
    Route::get('/{jemaat}/edit', ['as' => 'edit', 'uses' => 'JemaatController@edit'])->middleware('permission:update jemaat');
});

Route::group(['prefix'=>'baptis','as'=>'baptis.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'BaptisController@index'])->middleware('permission:read baptis');
    Route::post('', ['as' => 'store', 'uses' => 'BaptisController@store'])->middleware('permission:create baptis');
    Route::get('/create', ['as' => 'create', 'uses' => 'BaptisController@create'])->middleware('permission:create baptis');
    Route::get('/{baptis}', ['as' => 'show', 'uses' => 'BaptisController@show'])->middleware('permission:read baptis');
    Route::put('/{baptis}', ['as' => 'update', 'uses' => 'BaptisController@update'])->middleware('permission:update baptis');
    Route::delete('/{baptis}', ['as' => 'destroy', 'uses' => 'BaptisController@destroy'])->middleware('permission:delete baptis');
    Route::get('/{baptis}/edit', ['as' => 'edit', 'uses' => 'BaptisController@edit'])->middleware('permission:update baptis');
});

Route::group(['prefix'=>'sidi','as'=>'sidi.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'SidiController@index'])->middleware('permission:read sidi');
    Route::post('', ['as' => 'store', 'uses' => 'SidiController@store'])->middleware('permission:create sidi');
    Route::get('/create', ['as' => 'create', 'uses' => 'SidiController@create'])->middleware('permission:create sidi');
    Route::get('/{sidi}', ['as' => 'show', 'uses' => 'SidiController@show'])->middleware('permission:read sidi');
    Route::put('/{sidi}', ['as' => 'update', 'uses' => 'SidiController@update'])->middleware('permission:update sidi');
    Route::delete('/{sidi}', ['as' => 'destroy', 'uses' => 'SidiController@destroy'])->middleware('permission:delete sidi');
    Route::get('/{sidi}/edit', ['as' => 'edit', 'uses' => 'SidiController@edit'])->middleware('permission:update sidi');
});

Route::group(['prefix'=>'nikah','as'=>'nikah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'NikahController@index'])->middleware('permission:read nikah');
    Route::post('', ['as' => 'store', 'uses' => 'NikahController@store'])->middleware('permission:create nikah');
    Route::get('/create', ['as' => 'create', 'uses' => 'NikahController@create'])->middleware('permission:create nikah');
    Route::get('/{nikah}', ['as' => 'show', 'uses' => 'NikahController@show'])->middleware('permission:read nikah');
    Route::put('/{nikah}', ['as' => 'update', 'uses' => 'NikahController@update'])->middleware('permission:update nikah');
    Route::delete('/{nikah}', ['as' => 'destroy', 'uses' => 'NikahController@destroy'])->middleware('permission:delete nikah');
    Route::get('/{nikah}/edit', ['as' => 'edit', 'uses' => 'NikahController@edit'])->middleware('permission:update nikah');
});

Route::group(['prefix'=>'pengumuman','as'=>'pengumuman.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'PengumumanController@index'])->middleware('permission:read pengumuman');
    Route::post('', ['as' => 'store', 'uses' => 'PengumumanController@store'])->middleware('permission:create pengumuman');
    Route::get('/create', ['as' => 'create', 'uses' => 'PengumumanController@create'])->middleware('permission:create pengumuman');
    Route::get('/{pengumuman}', ['as' => 'show', 'uses' => 'PengumumanController@show'])->middleware('permission:read pengumuman');
    Route::put('/{pengumuman}', ['as' => 'update', 'uses' => 'PengumumanController@update'])->middleware('permission:update pengumuman');
    Route::delete('/{pengumuman}', ['as' => 'destroy', 'uses' => 'PengumumanController@destroy'])->middleware('permission:delete pengumuman');
    Route::get('/{pengumuman}/edit', ['as' => 'edit', 'uses' => 'PengumumanController@edit'])->middleware('permission:update pengumuman');
});

Route::group(['prefix'=>'ibadah','as'=>'ibadah.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'IbadahController@index'])->middleware('permission:read ibadah');
    Route::post('', ['as' => 'store', 'uses' => 'IbadahController@store'])->middleware('permission:create ibadah');
    Route::get('/create', ['as' => 'create', 'uses' => 'IbadahController@create'])->middleware('permission:create ibadah');
    Route::get('/{ibadah}', ['as' => 'show', 'uses' => 'IbadahController@show'])->middleware('permission:read ibadah');
    Route::put('/{ibadah}', ['as' => 'update', 'uses' => 'IbadahController@update'])->middleware('permission:update ibadah');
    Route::delete('/{ibadah}', ['as' => 'destroy', 'uses' => 'IbadahController@destroy'])->middleware('permission:delete ibadah');
    Route::get('/{ibadah}/edit', ['as' => 'edit', 'uses' => 'IbadahController@edit'])->middleware('permission:update ibadah');
});

Route::group(['prefix'=>'keuangan','as'=>'keuangan.'], function(){
    Route::get('', ['as' => 'index', 'uses' => 'KeuanganController@index'])->middleware('permission:read keuangan');
    Route::post('', ['as' => 'store', 'uses' => 'KeuanganController@store'])->middleware('permission:create keuangan');
    Route::get('/create', ['as' => 'create', 'uses' => 'KeuanganController@create'])->middleware('permission:create keuangan');

resources/views/kategori/create.blade.php
@extends('layouts.base')

@section('css')
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

@section('title_head')
    Tambah Rayon / Kategori Ibadah
@endsection

@section('bread')
    <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('kategori.index') }}">Rayon / Kategori Ibadah</a></li>
    <li class="breadcrumb-item active">Tambah Rayon / Kategori Ibadah</li>
@endsection

@section('content')
<form action="{{ route('kategori.store') }}" class="form-horizontal" method="POST">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Rayon / Kategori Ibadah</h3>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label for="kategori" class="col-sm-3 col-form-label">Rayon / Kategori Ibadah</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="kategori" name="kategori" placeholder="Nama Rayon / Kategori">
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{ route('kategori.index') }}" class="btn btn-default float-right">Batal</a>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@section('javascript')
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<!-- InputMask -->
<script src="{{ asset('plugins/inputmask/min/jquery.inputmask.bundle.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<!-- date-range-picker -->
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<script>
    $(function(){
        $('.datepick').datetimepicker({
            format: 'L'
        });
        $('[data-mask]').inputmask();
        $('.select2').select2({
            theme: 'bootstrap4'
        });
    });
</script>
@endsection

resources/views/kategori/edit.blade.php
@extends('layouts.base')

@section('css')
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

@section('title_head')
    Ubah Rayon / Kategori Ibadah
@endsection

@section('bread')
    <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('kategori.index') }}">Rayon / Kategori Ibadah</a></li>
    <li class="breadcrumb-item active">Ubah Rayon / Kategori Ibadah</li>
@endsection

@section('content')
<form action="{{ route('kategori.update', $kategori->id) }}" class="form-horizontal" method="POST">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Ubah Rayon / Kategori Ibadah</h3>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label for="kategori" class="col-sm-3 col-form-label">Rayon / Kategori Ibadah</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="kategori" name="kategori" placeholder="Nama Rayon / Kategori" value="{{ $kategori->kategori }}">
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{ route('kategori.index') }}" class="btn btn-default float-right">Batal</a>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@section('javascript')
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<!-- InputMask -->
<script src="{{ asset('plugins/inputmask/min/jquery.inputmask.bundle.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<!-- date-range-picker -->
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<script>
    $(function(){
        $('.datepick').datetimepicker({
            format: 'L'
        });
        $('[data-mask]').inputmask();
        $('.select2').select2({
            theme: 'bootstrap4'
        });
    });
</script>
@endsection

resources/views/kategori/list.blade.php
@extends('layouts.base')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('title_head')
    Rayon / Kategori Ibadah
@endsection

@section('bread')
    <li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
    <li class="breadcrumb-item active">Rayon / Kategori Ibadah</li>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Data Rayon / Kategori Ibadah</h3>
                <div class="card-tools">
                    @can('create katibadah')
                    <a href="{{ route('kategori.create') }}" class="btn btn-block btn-sm bg-gradient-success"><i class="fas fa-plus"></i> Tambah Rayon / Kategori Ibadah</a>                        
                    @endcan
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-striped datatabel">
                <thead>
                <tr>
                    <th>Rayon / Kategori Ibadah</th>
                    <th style="width: 20%">Aksi</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($kategoris as $kategori)
                    <tr>
                        <td>{{ $kategori->kategori }}</td>
                        <td>
                            <div class="btn-group">
                                @can('update katibadah')
                                <a href="{{ route('kategori.edit',$kategori->id) }}" class="btn btn-sm bg-gradient-info"><i class="fas fa-pencil-alt"></i> Ubah</a>                                    
                                @endcan
                                @can('delete katibadah')
                                <button type="button" class="btn btn-sm bg-gradient-danger" data-toggle="modal" data-target="#confrimModal{{ $kategori->id }}"><i class="fas fa-trash"></i> Hapus</button>                                    
                                @endcan
                            </div>
                        </td>
                    </tr>
                    <div class="modal fade" id="confrimModal{{ $kategori->id }}">
                        <div class="modal-dialog">
                            <div class="modal-content bg-danger">
                                <div class="modal-header">
                                    <h4 class="modal-title">Konfirmasi</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Apakah Anda Yakin Ingin Menghapus Kategori Ibadah <strong>{{ $kategori->kategori }}</strong></p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    <form action="{{ route('kategori.destroy',$kategori->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-outline-light">Ya, Saya Yakin</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </tbody>
                
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('javascript')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script>
    $(function(){
        $(".datatabel").DataTable({
            "ordering": false,
        });
    });
</script>
@endsection